In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
import kagglehub as kgh

path = kgh.dataset_download("mobeenfatimah/student-exam-performance-and-success-dataset")
print(f"Path to dataset files: {os.listdir(path)}")

ds_path = os.path.join(path , "student_exam_performance.csv")

df = pd.read_csv(ds_path)

Path to dataset files: ['student_exam_performance.csv']

In [10]:
print(f"Dataset shape : {df.shape}")

Dataset shape : (100000, 44)

In [11]:
df.head()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 44 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   student_id                  100000 non-null  str
 1   age                         100000 non-null  int64
 2   gender                      100000 non-null  str
 3   education_level             100000 non-null  str
 4   school_type                 100000 non-null  str
 5   family_income               100000 non-null  str
 6   parent_education            93474 non-null   str
 7   urban_rural                 100000 non-null  str
 8   previous_exam_score         100000 non-null  float64
 9   previous_gpa                92207 non-null   float64
 10  attendance_percentage       90137 non-null   float64
 11  assignment_completion_rate  100000 non-null  float64
 12  class_participation         100000 non-null  str
 13  study_hours_per_day         100000 non-null  float64
 14  self_study_hours            100000 non-null  float64
 15  private_tuition             100000 non-null  int64
 16  online_learning_hours       100000 non-null  float64
 17  study_consistency           100000 non-null  str
 18  study_environment           100000 non-null  str
 19  study_method                100000 non-null  str
 20  revision_frequency          100000 non-null  str
 21  practice_tests_completed    100000 non-null  int64
 22  notes_quality               91593 non-null   str
 23  sleep_hours                 100000 non-null  float64
 24  sleep_quality               93006 non-null   str
 25  daily_screen_time           100000 non-null  float64
 26  physical_activity_hours     100000 non-null  float64
 27  break_frequency             100000 non-null  str
 28  stress_level                100000 non-null  int64
 29  motivation_level            100000 non-null  str
 30  internet_access             100000 non-null  int64
 31  device_availability         97035 non-null   str
 32  educational_app_usage       100000 non-null  str
 33  online_course_hours         100000 non-null  float64
 34  exam_difficulty             100000 non-null  str
 35  exam_preparation_days       100000 non-null  int64
 36  questions_attempted         100000 non-null  int64
 37  questions_correct           100000 non-null  int64
 38  time_management_score       90387 non-null   float64
 39  exam_anxiety_level          100000 non-null  float64
 40  exam_score                  100000 non-null  float64
 41  performance_grade           100000 non-null  str
 42  pass_status                 100000 non-null  str
 43  performance_level           100000 non-null  str
dtypes: float64(14), int64(8), str(22)
memory usage: 33.6 MB

In [14]:
print(f"Null values is  {df.isnull().sum()}")
print(f"Duplicate rows : {df.duplicated().sum()}")

train_df = df

Null values is  student_id                       0
age                              0
gender                           0
education_level                  0
school_type                      0
family_income                    0
parent_education              6526
urban_rural                      0
previous_exam_score              0
previous_gpa                  7793
attendance_percentage         9863
assignment_completion_rate       0
class_participation              0
study_hours_per_day              0
self_study_hours                 0
private_tuition                  0
online_learning_hours            0
study_consistency                0
study_environment                0
study_method                     0
revision_frequency               0
practice_tests_completed         0
notes_quality                 8407
sleep_hours                      0
sleep_quality                 6994
daily_screen_time                0
physical_activity_hours          0
break_frequency                  0
stress_level                     0
motivation_level                 0
internet_access                  0
device_availability           2965
educational_app_usage            0
online_course_hours              0
exam_difficulty                  0
exam_preparation_days            0
questions_attempted              0
questions_correct                0
time_management_score         9613
exam_anxiety_level               0
exam_score                       0
performance_grade                0
pass_status                      0
performance_level                0
dtype: int64
Duplicate rows : 0

### Handle missing values

In [18]:

num_cols = ['time_management_score' , 'attendance_percentage' , 'previous_gpa' ]

df[num_cols] = df[num_cols].fillna(df[num_cols].median())

df.head()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,79.00,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low

In [19]:
str_cols = ['parent_education','device_availability','sleep_quality','notes_quality']

df[str_cols] = df[str_cols].fillna('Missing')

print(f"Null values is  {df.isnull().sum()}")

Null values is  student_id                    0
age                           0
gender                        0
education_level               0
school_type                   0
family_income                 0
parent_education              0
urban_rural                   0
previous_exam_score           0
previous_gpa                  0
attendance_percentage         0
assignment_completion_rate    0
class_participation           0
study_hours_per_day           0
self_study_hours              0
private_tuition               0
online_learning_hours         0
study_consistency             0
study_environment             0
study_method                  0
revision_frequency            0
practice_tests_completed      0
notes_quality                 0
sleep_hours                   0
sleep_quality                 0
daily_screen_time             0
physical_activity_hours       0
break_frequency               0
stress_level                  0
motivation_level              0
internet_access               0
device_availability           0
educational_app_usage         0
online_course_hours           0
exam_difficulty               0
exam_preparation_days         0
questions_attempted           0
questions_correct             0
time_management_score         0
exam_anxiety_level            0
exam_score                    0
performance_grade             0
pass_status                   0
performance_level             0
dtype: int64